language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t manvinagdev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true manvinagdev/react-test npm test -- --coverage

after_success:
  - docker build -t manvinagdev/multi-client ./client
  - docker build -t manvinagdev/multi-nginx ./nginx
  - docker build -t manvinagdev/multi-server ./server
  - docker build -t manvinagdev/multi-worker ./worker
  # Docker login
  - echo "$Docker_PASSWORD" | docker login -u "$Docker_ID" --password-stdin
  - docker push manvinagdev/multi-client
  - docker push manvinagdev/multi-nginx
  - docker push manvinagdev/multi-server
  - docker push manvinagdev/multi-worker